openapi: 3.0.0
info:
  title: LinkedIn Automation API
  version: 1.0.0
  description: API für die LinkedIn-Automatisierung mit KI-Agenten

servers:
  - url: http://localhost:3001/api
    description: Lokaler Entwicklungsserver
  - url: https://api.linkedin-automation.com/api
    description: Produktionsserver

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ContentStrategy:
      type: object
      properties:
        trends:
          type: array
          items:
            type: string
        recommendations:
          type: array
          items:
            type: string

    EngagementAnalysis:
      type: object
      properties:
        metrics:
          type: object
          properties:
            likes:
              type: number
            comments:
              type: number
            shares:
              type: number
        insights:
          type: array
          items:
            type: string

    NetworkGrowth:
      type: object
      properties:
        growthRate:
          type: number
        recommendations:
          type: array
          items:
            type: string

paths:
  /agents/content-strategy:
    post:
      summary: Content-Strategie generieren
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keywords:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Erfolgreich
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentStrategy'
        '401':
          description: Nicht autorisiert
        '429':
          description: Zu viele Anfragen

  /agents/engagement-analysis:
    post:
      summary: Engagement-Analyse durchführen
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postData:
                  type: object
      responses:
        '200':
          description: Erfolgreich
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngagementAnalysis'
        '401':
          description: Nicht autorisiert
        '429':
          description: Zu viele Anfragen

  /agents/network-growth:
    post:
      summary: Netzwerk-Wachstum analysieren
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                profileData:
                  type: object
      responses:
        '200':
          description: Erfolgreich
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkGrowth'
        '401':
          description: Nicht autorisiert
        '429':
          description: Zu viele Anfragen 